### ISSUE TITLE
有些不懂

### ISSUE THREAD

**Issue by zhangYHBox** [vains-Sofia/vains-cloud-template#4]
如果不引用spring-boot-starter-oauth2-client
yml  里面不配置

  security:
    oauth2:
      client:
        registration: * 相关信息

**Comment by vains-Sofia** [comment]
> 如果不引用spring-boot-starter-oauth2-client yml里面不配置
> 
> 安全性： oauth2： 客户端： 注册：* 相关信息

        在gateway网关中引入oauth2-client的目的就是将网关当做认证中心的一个客户端，那么每次通过网关请求服务时框架会检测是否登录，如果没有登录则会跳转至登录页；而yml中的这些配置则是配置你从认证中心申请的客户端信息。
        在认证中心中引入则是使用了Spring authorization server的联合登录功能，可直接通过第三方的认证中心认证。

**Comment by vains-Sofia** [comment]
> 如果不引用spring-boot-starter-oauth2-client yml 里面不配置
> 
> security: oauth2: client: registration: * 相关信息

>在gateway网关中引入oauth2-client的目的就是将网关当做认证中心的一个客户端，那么每次通过网关请求服务时框架会检测是否登录，如果没有登录则会跳转至登录页；而yml中的这些配置则是配置你从认证中心申请的客户端信息。
>在认证中心中引入则是使用了Spring authorization server的联合登录功能，可直接通过第三方的认证中心认证。

**Comment by zhangYHBox** [comment]
谢谢回答，主要是看了其他的cloud，他里面没有引入这些，自己尝试移除这些配置，遇到困难理解不透搞不定

**Comment by vains-Sofia** [comment]
没事儿，能帮到你我感到很高兴 
![Uploading 3DBD5C3D.png…]()

**Comment by vains-Sofia** [comment]
没事儿，能帮到你我感到很高兴
~(～￣▽￣)～
